### ISSUE TITLE
Clean up or ignore generated test files

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/goes-glm#13]
**Describe the bug**
The test suite creates files that **git** can pick up.

**To reproduce**

```shell
$ pytest > /dev/null 2>&1 && git status --short
?? tests/data-files/events.parquet
?? tests/data-files/flashes.parquet
?? tests/data-files/groups.parquet
```

**Expected behavior**
Files should be created in a temporary directory, created in a `.gitignore`'d directory, or explicitly deleted after test execution.

**Comment by m-mohr** [comment]
Yes, that will be done as part of #6 like it is in the noaa mrms qpe package. I just made the tests run for now :-)

**Comment by m-mohr** [comment]
Done
