### ISSUE TITLE
Add documentation strings

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/goes-glm#15]
All public functions (e.g. `stactools.goes_glm.parquet.create_asset` should have a documentation string describing their purpose. It doesn't need to be a fully fleshed-out example w/ args, return type, etc; just a small blurb is fine for now.

**Comment by m-mohr** [comment]
Can surely add the doc strings (regardless of the following comment).

Although now that you talk about "public" functions, I'm wondering whether they should actually be public or not.
