### ISSUE TITLE
Remove creation date from Item IDs

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/goes-glm#19]
Request to remove the creation datetime from the Item IDs. This is to avoid multiple Items if the data is reprocessed in the future. See [this issue](https://github.com/stactools-packages/modis/issues/87) on the MODIS repo for discussion.

 The current IDs are taken directly from the source filenames and end with the creation datetime, for example:
`OR_GLM-L2-LCFA_G16_s20203662359400_e20210010000004_c20210010000030`

The proposed change would modify the ID to become:
`OR_GLM-L2-LCFA_G16_s20203662359400_e20210010000004`

**Comment by m-mohr** [comment]
Valid point. Should that be an option? Or is the creation time always irrelevant?

**Comment by pjhartzell** [comment]
Either seems fine. If it is an option, I would say make exclusion of the creation/processing date the default.

**Comment by m-mohr** [comment]
Implemented with commit https://github.com/stactools-packages/goes-glm/commit/f2d0e4b9ac2fc332d7f6fbae6008d7d2a1578594
