### ISSUE TITLE
netCDF files (and conversion to a cloud-optimized format)

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/goes-glm#3]
- netCDF v4 according to docs and GDAL (CF v1.7)
- Panoply and rasterio report Hierarchical Data Format, version 5
- QGIS can't read these files!
- gdalinfo can't read it, you need to use gdalmdiminfo or ogrinfo instead
=> vestor data cube with point-data

> This product does not conform to the netCDF classic data model because it makes use of multiple unlimited dimensions.

Describes unlimited dimensions: https://docs.unidata.ucar.edu/netcdf-c/current/unlimited_dims.html

Global attributes such as id, featureType, datetimes etc. Can be used for collection and item metadata. See #4 for details.

It has a lot of variables, see Table 5.26.6-2. Each variable has only one dimension though. They are grouped as follows:

- Dim `number_of_flashes` (flash_count: 179)
  - flash_id
  - flash_time_offset_of_first_event
  - flash_time_offset_of_last_event
  - flash_frame_time_offset_of_first_event
  - flash_frame_time_offset_of_last_event
  - flash_lat
  - flash_lon
  - flash_area
  - flash_energy
  - flash_quality_flag
- Dim `number_of_groups` (group_count: 3706)
  - group_id
  - group_time_offset
  - group_frame_time_offset
  - group_lat
  - group_lon
  - group_area
  - group_energy
  - group_parent_flash_id
  - group_quality_flag
- Dim `number_of_events` (event_count: 11236)
  - event_id
  - event_time_offset
  - event_lat
  - event_lon
  - event_energy
  - event_parent_group_id
- Dim `number_of_time_bounds`
  - product_time_bounds (662731180,662731200.469121) -> seconds since 2000-01-01 12:00:00
- Dim `number_of_field_of_view_bounds` -> metadata, i.e. the bounding box
  - lat_field_of_view_bounds (66.56,-66.56)
  - lon_field_of_view_bounds (-141.56,-8.44)
- Dim `number_of_wavelength_bounds`
  - lightning_wavelength_bounds (776.87,777.87) -> FWHM

Additional variables with a scalar value, but additional metadata assigned:
- algorithm_dynamic_input_data_container (invalid value, seems mostly about metadata)
- algorithm_product_version_container (invalid value, seems mostly about metadata)
- event_count ^
- flash_count ^
- flash_time_threshold (3,329999924)
- goes_lat_lon_projection (invalid value, seems mostly about metadata)
- group_count ^
- group_time_threshold (0,0)
- lat_field_of_view (0) / lon_field_of_view (-75,0) -> metadata, i.e. the center coordinate
- lightning_wavelength (777,3699951)
- nominal_satellite_height (35786,02344)
- nominal_satellite_subpoint_lat (0,0)
- nominal_satellite_subpoint_lon (-75,19999695)
- percent_navigated_L1b_events (1,0)
- percent_uncorrectable_L0_errors (0,0)
- processing_parm_version_container (invalid value, seems mostly about metadata)
- product_time (662731180,0) -> seconds since 2000-01-01 12:00:00
- yaw_flip_flag (0)

Example in brackets are from the G16 example file.

Potential solution:
- provide original netCDF
- provide 3 (or 1?) geoparquet files (flashes, groups, events)
- add (all?) additional data into STAC metadata

The main question here is what people actually use? I'm not a domain expert here and unsure about how people would use this.

Direct conversion is not possible, we need to rewrite this into columnar format:
- gdalmdimtranslate to GTIFF -> Sementation fault
- ogr2ogr to Parquet -> Can't read netCDF

**Comment by m-mohr** [comment]
@TomAugspurger Do you have a clue how I can set version to 2.6?
I'm using `geopandas.GeoDataFrame.to_parquet`, but as it already has a `version` parameter for the geoparquet version, I can't use kwargs to pass through the version to arrow?

```py
kwargs = {"version":"2.6"}
dataframe.to_parquet(file, **kwargs)
# => ValueError: version must be one of: 0.1.0, 0.4.0
```

**Comment by TomAugspurger** [comment]
Ah that's unfortunate. GeoDataFrame.to_parquet's `version` is used for the `geoparquet` version, and clashes with the `version` argument used by Table.to_parquet: https://github.com/geopandas/geopandas/blob/28462f8e7fd893e01be52f444e142a1a00c36f8e/geopandas/io/arrow.py#L284

I'll open an issue.

**Comment by m-mohr** [comment]
Thank you, was about to do the same but please go ahead @TomAugspurger .

How do we proceed? I have code ready that exports timestamps, the only issue now is that it is not precise enough and we'd likely need to wait for a fix?

**Comment by TomAugspurger** [comment]
https://github.com/geopandas/geopandas/issues/2495.

I included a workaround there, that uses a private geopandas API. Not idealy, but it might be the best for now.

```python
In [4]: table = geopandas.io.arrow._geopandas_to_arrow(df)

In [5]: import pyarrow.parquet as pq

In [6]: pq.write_table(table, "out.parquet", version="2.6")
```
